version: '3.8'

services:
  db:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  
  server:
    container_name: golang-server
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      - MODE=production
    env_file:
      - .env
    depends_on:
      - db


volumes:
  db:
    driver: local